apiVersion: apps/v1
kind: Deployment
metadata:
  name: transport-ml-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transport-ml-api
  template:
    metadata:
      labels:
        app: transport-ml-api
    spec:
      containers:
        - name: api
          image: infrastructure-ml-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
