apiVersion: v1
kind: Service
metadata:
  name: transport-ml-api-service
spec:
  type: NodePort
  selector:
    app: transport-ml-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007
